### ISSUE TITLE
Update link to VSCode Marketplace

### ISSUE THREAD

**Issue by wahyuandrey** [maxibanki/vscode-postscript#2]
Hi. Your extension helps me a lot in my project.

I found 1 minor annoyance, that your link in about section points to https://marketplace.visualstudio.com/items?itemName=maxibanki.postscript which is obviously wrong.

Please change link to correct one: https://marketplace.visualstudio.com/items?itemName=mxschmitt.postscript . It would be such a shame if people cannot install your extension due to wrong hyperlink.

Thanks for this great extension!

![2022-09-06 142608](https://user-images.githubusercontent.com/52889680/188573493-c3440e54-2bb9-43ba-9b1a-2007bb1c3084.jpg)

**Comment by mxschmitt** [comment]
Fixed, thanks and happy to hear!
